### ISSUE TITLE
example lotka.py error

### ISSUE THREAD

**Issue by gamafreire** [Zulko/ddeint#3]
--> python lotka.py
Computing for d=0.00
capi_return is NULL
Call-back cb_f_in_dvode__user__routines failed.
Traceback (most recent call last):
  File "lo.py", line 19, in <module>
    yy = ddeint(model,g,tt,fargs=(d,))
  File "/usr/local/lib/python2.7/site-packages/ddeint/ddeint.py", line 140, in ddeint
    results = [dde_.integrate(dde_.t + dt) for dt in np.diff(tt)]
  File "/usr/local/lib/python2.7/site-packages/ddeint/ddeint.py", line 62, in integrate
    scipy.integrate.ode.integrate(self,t,step,relax)
  File "/usr/local/lib/python2.7/site-packages/scipy/integrate/_ode.py", line 408, in integrate
    self.f_params, self.jac_params)
  File "/usr/local/lib/python2.7/site-packages/scipy/integrate/_ode.py", line 865, in run
    y1, t, istate = self.runner(*args)
  File "/usr/local/lib/python2.7/site-packages/ddeint/ddeint.py", line 56, in f2
    return f(self.Y,t,*args)
  File "lo.py", line 8, in model
    x,y = Y(t)
  File "/usr/local/lib/python2.7/site-packages/ddeint/ddeint.py", line 42, in __call__
    return (self.g(t) if (t<=self.tc) else self.itpr(t))
  File "/usr/local/lib/python2.7/site-packages/scipy/interpolate/polyint.py", line 79, in __call__
    y = self._evaluate(x)
  File "/usr/local/lib/python2.7/site-packages/scipy/interpolate/interpolate.py", line 608, in _evaluate
    y_new = self._call(self, x_new)
  File "/usr/local/lib/python2.7/site-packages/scipy/interpolate/interpolate.py", line 566, in _call_linear
    y_lo = self._y[lo]
IndexError: index 2 is out of bounds for axis 0 with size 2

**Comment by gamafreire** [comment]
Thank you very much.
The error is connected to an older pull open request, so my work environment is:

Python 2.7.13 (default, May  2 2017, 22:42:15)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import scipy
>>> scipy.__version__
'0.19.1'

**Comment by darioizzo** [comment]
same error on my machine with linux and py3. Is this ddeint package maintained still?

**Comment by Zulko** [comment]
It's not maintained, sorry, it was just a quick hack from around 5 years ago (see [this blog post](https://zulko.wordpress.com/2013/03/01/delay-differential-equations-easy-with-python/)).

I'm sure that the error could be fixed (the whole package is only 40 lines of code) but if you can't find how, try alternatives like pyDDE and pydelay.

**Comment by Zulko** [comment]
Fixed in the new version
